/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *table1;
  GtkWidget *hscrollbar1;
  GtkWidget *hscale3;
  GtkWidget *vscale1;
  GtkWidget *checkbutton1;
  GtkWidget *hbox4;
  GtkWidget *label4;
  GtkWidget *optionmenu2;
  GtkWidget *menu2;
  GtkWidget *top1;
  GtkWidget *bottom1;
  GtkWidget *left1;
  GtkWidget *right1;
  GtkWidget *hbox3;
  GtkWidget *label3;
  GtkWidget *optionmenu1;
  GtkWidget *menu1;
  GtkWidget *cont1;
  GtkWidget *discont1;
  GtkWidget *delay1;
  GtkWidget *hbox2;
  GtkWidget *label2;
  GtkWidget *hscale2;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkWidget *hscale1;
  GtkWidget *hseparator1;
  GtkWidget *btnQuit;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), "window1");
  gtk_window_set_default_size (GTK_WINDOW (window1), 500, 400);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 10);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);

  hscrollbar1 = gtk_hscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 100, 0.1, 10, 0)));
  gtk_widget_show (hscrollbar1);
  gtk_table_attach (GTK_TABLE (table1), hscrollbar1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK), 0, 0);

  hscale3 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 100, 0.1, 10, 0)));
  gtk_widget_show (hscale3);
  gtk_table_attach (GTK_TABLE (table1), hscale3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  vscale1 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 100, 0.1, 10, 0)));
  gtk_widget_show (vscale1);
  gtk_table_attach (GTK_TABLE (table1), vscale1, 0, 1, 0, 2,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 20, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale1), TRUE);

  checkbutton1 = gtk_check_button_new_with_mnemonic ("Display value on scale widgets");
  gtk_widget_show (checkbutton1);
  gtk_box_pack_start (GTK_BOX (vbox1), checkbutton1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton1), 5);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton1), TRUE);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox4, TRUE, TRUE, 0);

  label4 = gtk_label_new ("scale value position:");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label4), 5, 0);

  optionmenu2 = gtk_option_menu_new ();
  gtk_widget_show (optionmenu2);
  gtk_box_pack_start (GTK_BOX (hbox4), optionmenu2, TRUE, TRUE, 0);

  menu2 = gtk_menu_new ();

  top1 = gtk_menu_item_new_with_mnemonic ("top");
  gtk_widget_show (top1);
  gtk_container_add (GTK_CONTAINER (menu2), top1);

  bottom1 = gtk_menu_item_new_with_mnemonic ("bottom");
  gtk_widget_show (bottom1);
  gtk_container_add (GTK_CONTAINER (menu2), bottom1);

  left1 = gtk_menu_item_new_with_mnemonic ("left");
  gtk_widget_show (left1);
  gtk_container_add (GTK_CONTAINER (menu2), left1);

  right1 = gtk_menu_item_new_with_mnemonic ("right");
  gtk_widget_show (right1);
  gtk_container_add (GTK_CONTAINER (menu2), right1);

  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu2), menu2);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, TRUE, TRUE, 0);

  label3 = gtk_label_new ("scale update policy:");
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 0);

  optionmenu1 = gtk_option_menu_new ();
  gtk_widget_show (optionmenu1);
  gtk_box_pack_start (GTK_BOX (hbox3), optionmenu1, TRUE, TRUE, 0);

  menu1 = gtk_menu_new ();

  cont1 = gtk_menu_item_new_with_mnemonic ("Cont");
  gtk_widget_show (cont1);
  gtk_container_add (GTK_CONTAINER (menu1), cont1);

  discont1 = gtk_menu_item_new_with_mnemonic ("Discont");
  gtk_widget_show (discont1);
  gtk_container_add (GTK_CONTAINER (menu1), discont1);

  delay1 = gtk_menu_item_new_with_mnemonic ("Delay");
  gtk_widget_show (delay1);
  gtk_container_add (GTK_CONTAINER (menu1), delay1);

  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu1), menu1);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 0);

  label2 = gtk_label_new ("scale digits:");
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  hscale2 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (1, 0, 5, 1, 1, 0)));
  gtk_widget_show (hscale2);
  gtk_box_pack_start (GTK_BOX (hbox2), hscale2, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (hscale2), 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  label1 = gtk_label_new ("scrollbar page size:");
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label1), 5, 0);

  hscale1 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 100, 1, 10, 0)));
  gtk_widget_show (hscale1);
  gtk_box_pack_start (GTK_BOX (hbox1), hscale1, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (hscale1), 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, FALSE, 0);

  btnQuit = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (btnQuit);
  gtk_box_pack_start (GTK_BOX (vbox1), btnQuit, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
  g_signal_connect ((gpointer) hscrollbar1, "value_changed",
                    G_CALLBACK (on_hscrollbar1_value_changed),
                    NULL);
  g_signal_connect ((gpointer) hscale3, "value_changed",
                    G_CALLBACK (on_hscale3_value_changed),
                    NULL);
  g_signal_connect ((gpointer) vscale1, "value_changed",
                    G_CALLBACK (on_vscale1_value_changed),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) top1, "activate",
                    G_CALLBACK (on_top1_activate),
                    NULL);
  g_signal_connect ((gpointer) bottom1, "activate",
                    G_CALLBACK (on_bottom1_activate),
                    NULL);
  g_signal_connect ((gpointer) left1, "activate",
                    G_CALLBACK (on_left1_activate),
                    NULL);
  g_signal_connect ((gpointer) right1, "activate",
                    G_CALLBACK (on_right1_activate),
                    NULL);
  g_signal_connect ((gpointer) cont1, "activate",
                    G_CALLBACK (on_cont1_activate),
                    NULL);
  g_signal_connect ((gpointer) discont1, "activate",
                    G_CALLBACK (on_discont1_activate),
                    NULL);
  g_signal_connect ((gpointer) delay1, "activate",
                    G_CALLBACK (on_delay1_activate),
                    NULL);
  g_signal_connect ((gpointer) hscale2, "value_changed",
                    G_CALLBACK (on_hscale2_value_changed),
                    NULL);
  g_signal_connect ((gpointer) hscale1, "value_changed",
                    G_CALLBACK (on_hscale1_value_changed),
                    NULL);
  g_signal_connect ((gpointer) btnQuit, "clicked",
                    G_CALLBACK (on_btnQuit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, table1, "table1");
  GLADE_HOOKUP_OBJECT (window1, hscrollbar1, "hscrollbar1");
  GLADE_HOOKUP_OBJECT (window1, hscale3, "hscale3");
  GLADE_HOOKUP_OBJECT (window1, vscale1, "vscale1");
  GLADE_HOOKUP_OBJECT (window1, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, optionmenu2, "optionmenu2");
  GLADE_HOOKUP_OBJECT (window1, menu2, "menu2");
  GLADE_HOOKUP_OBJECT (window1, top1, "top1");
  GLADE_HOOKUP_OBJECT (window1, bottom1, "bottom1");
  GLADE_HOOKUP_OBJECT (window1, left1, "left1");
  GLADE_HOOKUP_OBJECT (window1, right1, "right1");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, optionmenu1, "optionmenu1");
  GLADE_HOOKUP_OBJECT (window1, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (window1, cont1, "cont1");
  GLADE_HOOKUP_OBJECT (window1, discont1, "discont1");
  GLADE_HOOKUP_OBJECT (window1, delay1, "delay1");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, hscale2, "hscale2");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, hscale1, "hscale1");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window1, btnQuit, "btnQuit");

  return window1;
}

